### ISSUE TITLE
ImportError: libgnuradio-doa.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by junaid124** [EttusResearch/gr-doa#2]
import doa
  File "/usr/local/lib/python2.7/dist-packages/doa/__init__.py", line 41, in <module>
    from findmax_and_save import findmax_and_save
  File "/usr/local/lib/python2.7/dist-packages/doa/findmax_and_save.py", line 27, in <module>
    import doa_swig as doa
  File "/usr/local/lib/python2.7/dist-packages/doa/doa_swig.py", line 28, in <module>
    _doa_swig = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/doa/doa_swig.py", line 24, in swig_import_helper
    _mod = imp.load_module('_doa_swig', fp, pathname, description)
ImportError: libgnuradio-doa.so: cannot open shared object file: No such file or directory

>>> Done

**Comment by tfcollins** [comment]
Can you provide the install steps you used to install the OOT

**Comment by Maxgy** [comment]
I added this as a basic dependency in my pull request.  I basically just had to install doa before installing the repository.

**Comment by courtarro** [comment]
This looks to me like the original user forgot to run `sudo ldconfig` after installing.

**Comment by michaelld** [comment]
I agree with @courtarro . Not sure who can close this issue, but it's old enough and likely-as-not not a true issue with gr-doa but rather a user issue.

**Comment by michaelld** [comment]
closing as it's likely not an issue any longer ... if it is, please reopen and provide information as to what's going on
