### ISSUE TITLE
problems about the gr-doa simulation

### ISSUE THREAD

**Issue by cruisebzk** [EttusResearch/gr-doa#9]
## Issue Description ##

Hello:
when i simulate the gr-doa module without USRP X310, i find that  the simulation results are incorrect and it has the following rules.
The degree of angle which is the simulation parameter is theta. The computed results are sent to the 'QT GUI Vector Sink' module to show. We found that the estimation results is '90 + theta' if '90+theta' is less than 180 degree, and is  the '180-(90+theta-180)' if  '90+theta' is greater than 180 degree.

Where the problem maybe occurs?

thank you very much.

**Comment by tfcollins** [comment]
1D linear arrays cannot differentiate the direction of a signal when you exceed 90 (or -90) degrees off-boresight since the response of the array is identical (or mirrored). To get full 360 distinctions requires a 2D array.

**Comment by Sea-of-Silence** [comment]
thank you.
